# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Siege Squad Stats' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Siege Squad Stats
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
end
